#define CL_CX "cervix "
#define CL_NASO "nasopharyngeal "
#define CL_AM "amenorrhoea "
#define CL_AR "allergic rhinitis "
#define CL_AA "anaemia "
#define CL_AN "antenatal "
#define CL_ARR "arrhythmia "
#define CL_ASY "asymptomatic "
#define CL_AF "atrial fibrillation "
#define CL_CU "check up "
#define CL_CT "chemotherapy "
#define CL_CH "cholesterol "
#define CL_CHC "chronic cough "
#define CL_CD "crohns disease "
#define CL_COD "coeliac disease "
#define CL_CON "conjunctivitis "
#define CL_DE "deficiency "
#define CL_DB "diabetes "
#define CL_D "diarrhoea "
#define CL_DV "diarrhoea and vomiting "
#define CL_DIS "discharge "
#define CL_DYM "dysmenorrhoea "
#define CL_DU "dysuria "
#define CL_EC "endocervical "
#define CL_EP "epigastric pain "
#define CL_FD "fe deficiency "
#define CL_FU "follow up "
#define CL_GE "gastroenteritis "
#define CL_GCU "general check up "
#define CL_GO "gonorrhoea "
#define CL_GD "graves disease "
#define CL_HU "haematuria "
#define CL_HC "heamochromatosis "
#define CL_HECH "health check "
#define CL_HPY "helicobacter pylori "
#define CL_HIC "high cholesterol "
#define CL_YC "hypercholesterolaemia "
#define CL_YG "hyperglycaemia "
#define CL_YK "hyperkalaemia "
#define CL_YL "hyperlipidaemia "
#define CL_YN "hypernatraemia "
#define CL_HT "hypertension "
#define CL_YT "hyperthyroidism "
#define CL_OK "hypokalaemia "
#define CL_OL "hypolipaemia "
#define CL_ON "hyponatraemia "
#define CL_OT "hypothyroidism "
#define CL_HY "hysterectomy "
#define CL_IC "increased confusion "
#define CL_IBD "inflammatory bowel disease "
#define CL_IBS "inflammatory bowel syndrome "
#define CL_IDA "iron deficiency anaemia "
#define CL_IP "irregular period "
#define CL_JP "joint pain "
#define CL_L "lethargy "
#define CL_MCA "macrocytic anaemia "
#define CL_M "malaise "
#define CL_MP "menopausal "
#define CL_MTH "methotrexate "
#define CL_MH "microscopic haematuria "
#define CL_MO "monitoring "
#define CL_MY "myalgia "
#define CL_OCH "on chemo "
#define CL_OLI "on lipitor "
#define CL_OO "on oroxine "
#define CL_OR "on rosuvastatin "
#define CL_OS "on statin "
#define CL_OTH "on thyroxine "
#define CL_OW "on warfarin "
#define CL_ONY "onychomycosis "
#define CL_OSA "osteoarthritis "
#define CL_OST "osteoporosis "
#define CL_OE "otitis externa "
#define CL_PERI "perimenopausal "
#define CL_PC "persistent cough "
#define CL_PD "persistent diarrhoea "
#define CL_IMB "intermenstrual bleeding "
#define CL_PM "postmenopausal "
#define CL_PN "postnatal "
#define CL_QA "? anaemia "
#define CL_QC "? cause "
#define CL_QD "? diabetes "
#define CL_QU "? uti "
#define CL_QT "? thrush "
#define CL_SC "site cervix "
#define CL_SV "site vagina "
#define CL_SCB "site cervix  cervix looks benign "
#define CL_CLB "cervix looks benign "
#define CL_ST "sore throat "
#define CL_QS "? std "
#define CL_SCH "std check "
#define CL_STS "std screen "
#define CL_SIS "sti screen "
#define CL_T1 "type 1 dm "
#define CL_T1D "type 1 diabetes "
#define CL_T2 "type 2 dm "
#define CL_T2D "type 2 diabetes "
#define CL_C "covid 19 "
#define CL_CO "covid outbreak "
#define CL_CLC "close contact "
#define CL_CKD "chronic kidney disease "
#define CL_ACF "aged care facility "
#define CL_NFL "not fully legible "
