#define CL_AM "amenorrhoea "
#define CL_AO "add on "
#define CL_AQ "adrq "
#define CL_AR "allergic rhinitis "
#define CL_ANA "anaemia "
#define CL_AN "antenatal "
#define CL_ARR "arrhythmia "
#define CL_ASY "asymptomatic "
#define CL_AF "atrial fibrillation "
#define CL_ACP "atypical chest pain "
#define CL_BC "bartholins cyst "
#define CL_BA "baseline "
#define CL_B "benign "
#define CL_BRA "bradycardia "
#define CL_BR "bronchiectasis "
#define CL_CAP "ca prostate "
#define CL_CAR "cardiomyopathy "
#define CL_CE "cervix "
#define CL_CU "check up "
#define CL_CHT "chemotherapy "
#define CL_CHD "chest discomfort "
#define CL_CHP "chest pain "
#define CL_CHOL "cholesterol "
#define CL_CHR "chronic "
#define CL_CHRC "chronic cough "
#define CL_CHRD "chronic diarrhoea "
#define CL_CD "crohns disease "
#define CL_COD "coeliac disease "
#define CL_CF "confusion "
#define CL_CCF "congestive cardiac failure "
#define CL_CON "conjunctivitis "
#define CL_CONS "constipation "
#define CL_DEF "deficiency "
#define CL_DEM "dementia "
#define CL_DB "diabetes "
#define CL_DIAL "dialysis "
#define CL_D "diarrhoea "
#define CL_DV "diarrhoea and vomiting "
#define CL_DIS "discharge "
#define CL_DYL "dyslipidaemia "
#define CL_DYM "dysmenorrhoea "
#define CL_DYP "dyspareunia "
#define CL_DYS "dysuria "
#define CL_DF "dysuria and frequency "
#define CL_E "elevated "
#define CL_EC "endocervical "
#define CL_ENL "enlarged "
#define CL_ED "epigastric discomfort "
#define CL_EP "epigastric pain "
#define CL_EPIL "epilepsy "
#define CL_FTT "failure to thrive "
#define CL_FHD "family history of diabetes "
#define CL_FAT "fatigue "
#define CL_FD "fe deficiency "
#define CL_FEB "febrile "
#define CL_FERT "fertility "
#define CL_FU "follow up "
#define CL_FI "for investigation "
#define CL_FR "frequency "
#define CL_FAU "frequency and urgency "
#define CL_GE "gastroenteritis "
#define CL_GCU "general check up "
#define CL_GDM "gestational diabetes "
#define CL_GO "gonorrhoea "
#define CL_GD "graves disease "
#define CL_HAEM "haematuria "
#define CL_HAE "haemochromatosis "
#define CL_HA "haemorrhage "
#define CL_HECH "health check "
#define CL_HPY "helicobacter pylori "
#define CL_H "hepatitis "
#define CL_HC "high cholesterol "
#define CL_HYPC "hypercholesterolaemia "
#define CL_HYG "hyperglycaemia "
#define CL_HYK "hyperkalaemia "
#define CL_HYPL "hyperlipidaemia "
#define CL_HYN "hypernatraemia "
#define CL_HYP "hyperparathyroidism "
#define CL_HT "hypertension "
#define CL_HTH "hyperthyroid "
#define CL_HYT "hyperthyroidism "
#define CL_HOK "hypokalaemia "
#define CL_HOL "hypolipaemia "
#define CL_HON "hyponatraemia "
#define CL_HOP "hypoparathyroidism "
#define CL_HOT "hypothyroidism "
#define CL_HY "hysterectomy "
#define CL_I "incontinence "
#define CL_ICF "increased confusion "
#define CL_INC "indwelling catheter "
#define CL_INFE "infected "
#define CL_INF "infection "
#define CL_INFER "infertility "
#define CL_INFL "inflammatory "
#define CL_IBD "inflammatory bowel disease "
#define CL_IDA "iron deficiency anaemia "
#define CL_IRP "irregular periods "
#define CL_IRPB "irregular pv bleeding "
#define CL_IHD "ischaemic heart disease "
#define CL_J "jaundice "
#define CL_JP "joint pain "
#define CL_LE "lesion "
#define CL_L "lethargy "
#define CL_LAP "lower abdo pain "
#define CL_MC "macrocytic "
#define CL_MCA "macrocytic anaemia "
#define CL_M "malaise "
#define CL_MP "menopausal "
#define CL_MENP "menopause "
#define CL_MEN "menorrhagia "
#define CL_MTX "methotrexate "
#define CL_MIC "microcytic "
#define CL_MIA "microcytic anaemia "
#define CL_MH "microscopic haematuria "
#define CL_MONG "monitoring "
#define CL_MY "myalgia "
#define CL_NV "nausea and vomiting "
#define CL_OCH "on chemo "
#define CL_OD "on diuretics "
#define CL_OH "on hormones "
#define CL_OL "on lipitor "
#define CL_OM "on methotrexate "
#define CL_OO "on oroxine "
#define CL_OR "on rosuvastatin "
#define CL_OS "on statin "
#define CL_OT "on thyroxine "
#define CL_OW "on warfarin "
#define CL_ONY "onychomycosis "
#define CL_OSA "osteoarthritis "
#define CL_OST "osteoporosis "
#define CL_OTE "otitis externa "
#define CL_PAL "palpitations "
#define CL_PAN "pancreatitis "
#define CL_PP "pelvic pain "
#define CL_PERI "perimenopausal "
//#define CL_PN "peripheral neuropathy "
#define CL_PC "persistent cough "
#define CL_PERD "persistent diarrhoea "
#define CL_PIT "pituitary "
#define CL_PNE "pneumonia "
#define CL_PG "polyarthralgia "
#define CL_POLA "polyarthritis "
#define CL_POM "polymyalgia "
//#define CL_PCB "post coital bleeding "
#define CL_PU "polyuria "
#define CL_IMB "intermenstrual bleeding "
#define CL_PM "postmenopausal "
//#define CL_PMB "postmenopausal bleeding "
#define CL_PON "post natal "
#define CL_PV "post vasectomy "
#define CL_PVEN "post venesection "
#define CL_PH "postural hypotension "
#define CL_PRB "pr bleeding "
//#define CL_POC "pre op check "
//#define CL_POA "pre op assessment "
#define CL_PS "prev smear:  "
#define CL_PIN "primary infertility "
#define CL_PROC "productive cough "
//#define CL_PROG "progress "
#define CL_PROS "prostatitis "
#define CL_PSAR "psoriatic arthritis "
#define CL_PE "pulmonary embolism "
#define CL_QA "? anaemia "
#define CL_QCAP "? ca prostate "
#define CL_QC "? cause "
#define CL_QCOD "? coeliac disease "
#define CL_QDB "? diabetes "
#define CL_QEP "? ectopic pregnancy "
#define CL_QFI "? fungal infection "
#define CL_QGDM "? gestational diabetes "
#define CL_QGO "? gout "
#define CL_QINF "? infection "
#define CL_QMP "? menopausal "
#define CL_QMENO "? menopause "
#define CL_QM "? miscarriage "
#define CL_QONY "? onychomycosis "
#define CL_QPERI "? perimenopausal "
#define CL_QP "? pregnant "
#define CL_QPROG "? progress "
#define CL_QPROS "? prostatitis "
#define CL_QT "? thrush "
#define CL_QU "? uti "
//#define CL_RUTI "recent uti "
#define CL_REC "recurrent "
#define CL_RT "recurrent tonsillitis "
#define CL_RC "renal calculi "
#define CL_RF "renal failure "
#define CL_RI "renal impairment "
#define CL_RTR "renal transplant "
#define CL_RH "rheumatism "
#define CL_RA "rheumatoid arthritis "
#define CL_R "routine "
#define CL_SCN "screen "
#define CL_SCRG "screening "
#define CL_SIN "secondary infertility "
#define CL_SOB "shortness of breath "
#define CL_SC "site:cervix "
#define CL_SV "site:vagina "
#define CL_SCCLB "site:cervix cervix looks benign "
#define CL_ST "sore throat "
#define CL_STDC "std check "
#define CL_QS "? std "
#define CL_STP "sterile pyuria "
#define CL_STIS "sti screen "
#define CL_STDS "std screen "
#define CL_SPC "suprapubic catheter "
#define CL_SUD "suprapubic discomfort "
#define CL_SWE "swelling "
#define CL_SWO "swollen "
#define CL_TAC "tachycardia "
#define CL_THA "thalassaemia "
#define CL_TC "thrombocytopenia "
#define CL_T "thyroxine "
#define CL_TI "tiredness "
#define CL_T1 "type 1 diabetes "
#define CL_T1D "type 1 dm "
#define CL_T1DM "type 1 diabetes mellitus "
#define CL_T2 "type 2 diabetes "
#define CL_T2D "type 2 dm "
#define CL_T2DM "type 2 diabetes mellitus "
#define CL_UC "ulcerative colitis "
#define CL_UAF "urgency and frequency "
#define CL_UF "urinary frequency "
#define CL_VD "vaginal discharge "
#define CL_VAG "vaginitis "
#define CL_VOM "vomiting "
#define CL_W "warfarin "
#define CL_C "covid 19 "